const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }]

  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
}

module.exports = sidebars
